routes/web.php
<?php
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index')->name('home');

//  INI ROUTE UNTUK DI MASTER DATA

// route employee_master by admin
Route::resource('users', 'UserController');
Route::get('delete-user/{id}', 'UserController@deleteUser');
Route::get('export-userAdmin', 'UserController@userExportAdmin');
Route::post('import-userAdmin', 'UserController@userImportAdmin');
Route::get('download-template-admin', 'UserController@downloadtemplateAdmin');


// route untuk employe_master by hrd
Route::get('master-employee-detail', 'UserController@dataEmployee1');
Route::get('edit-employee/{id}', 'UserController@editEmployee');
Route::post('edit-employee/{id}', 'UserController@doEditEmployee');
Route::get('download-template-hrd', 'UserController@downloadtemplateHrd');

// route user
Route::get('profile', 'UserController@profile');
Route::post('users-search', 'UserController@searchuser');
Route::get('users-detail/{id}', 'UserController@detail')->name('users.detail');;



// INI ROUTE UNTUK DI MAIN MENU
// employee data
Route::get('data-employee', 'UserController@dataEmployee');



//  INI DI SETTINGS
//  update account profile
Route::get('update-account/{id}', 'UserController@updateAccount');
Route::post('update-account/{id}', 'UserController@doUpdateAccount');
Route::get('update-profile/{id}', 'UserController@updateProfile');
Route::post('update-profile/{id}', 'UserController@doUpdateProfile');

//  update and remove image
Route::post('user-update-picture', 'UserController@updatepicture');
Route::get('user-remove-picture/{id}', 'UserController@removepicture');

//  route roles
Route::resource('roles', 'RoleController');
Route::get('delete-role/{id}', 'RoleController@deleteRole');

// 
// route permission
Route::resource('permissions', 'PermissionController');

// route dashboard
Route::resource('dashboard', 'DashboardController');

// route todo list
Route::post('add-todo', 'DashboardController@addtodo');
Route::get('add-todo', function () {
    return view('dashboard');
});
Route::get('delete-todo/{id}', 'DashboardController@deletetodo');
// route attendance
Route::get('attendance', 'AbsenController@index');
Route::post('do_absen', 'AbsenController@doabsen'); 
// route employee performance
Route::get('employee-performance', 'EmployeePerformance@index');
// route import export add user
Route::get('export-user', 'UserController@userExport');
Route::post('import-user', 'UserController@userImport');
Route::get('download-template-user', 'UserController@downloadtemplate');
// route donwload template file user
route::get('donwload-files', 'DashboardController@donwloadFiles');
// route untuk master department
Route::get('master-department', 'DepartmentController@manageDepartment');
Route::post('department-search', 'DepartmentController@searchdepartment');

// 
Route::post('add-department', 'DepartmentController@adddepartment');
Route::get('add-department', function () {
    return view('department.add');
});
Route::get('delete-department/{id}', 'DepartmentController@deleteDepartment');
Route::get('edit-department/{id}', 'DepartmentController@editdepartment');
Route::post('edit-department/{id}', 'DepartmentController@doeditdepartment');

// route master division
Route::get('master-division', 'DivisionController@manageDivision');
Route::post('division-search', 'DivisionController@searchdivision');
Route::post('add-division', 'DivisionController@adddivision');
Route::get('add-division', function () {
    return view('division.index');
});
Route::get('delete-division/{id}', 'DivisionController@deleteDivision');
Route::get('edit-division/{id}', 'DivisionController@editdivision');
Route::post('edit-division/{id}', 'DivisionController@doeditdivision');

// route master position
Route::get('master-position', 'PositionController@managePosition');
Route::post('position-search', 'PositionController@searchposition');
Route::post('add-position', 'PositionController@addposition');
Route::get('add-position', function () {
    return view('position.index');
});
Route::get('delete-position/{id}', 'PositionController@deletePosition');
Route::get('edit-position/{id}', 'PositionController@editposition');
Route::post('edit-position/{id}', 'PositionController@doeditposition');


// route Submission form

// leave
Route::get('SubmissionForm-DayOffSubmission', 'SubmissionFormController@leaveSubindex');
Route::post('SubmissionForm-DayOffSubmission', 'SubmissionFormController@addDoLeaveType');
Route::get('leave-duration', 'SubmissionFormController@FindLTDuration');
Route::post('leaveSub-check', 'SubmissionFormController@leaveSubCheck');
Route::post('SubmissionForm-leaveSubmission-store', 'SubmissionFormController@leaveSubmissionStore');

// overtime
Route::get('/SubmissionForm-LoanSubmission', 'SubmissionFormController@loanSubIndex');
Route::get('/SubmissionForm-OvertimeSubmission', 'SubmissionFormController@OvertimeSubIndex');

// route reporting
Route::get('/Reporting-DayOffReport', 'ReportingController@DayOffRepindex');
Route::get('/Reporting-PaySlipReport', 'ReportingController@PaySlipRepindex');
Route::get('/Reporting-PaySlipReport-PaySlipDetail', 'ReportingController@PaySlipDetail');
Route::get('/Reporting-PaySlipReport-PaySlipDetail-Print', 'ReportingController@PaySlipPrint');
Route::get('/Reporting-OvertimeReport', 'ReportingController@OvertimeRepindex');
Route::get('/Reporting-LoanReport', 'ReportingController@LoanRepindex');


//  route Company Setting
Route::get('company-setting', 'CompanyController@manageCompany');

// route Approval
Route::get('approval', 'ApprovalController@index');


//salary_level_master
Route::get('/masterdata-payrollmaster-salarylevelmaster', 'PayrollMasterController@SalaryLevelMasterIndex');
Route::post('/masterdata-payrollmaster-salarylevelmaster-store', 'PayrollMasterController@SalaryLevelMasterStore');
Route::get('/masterdata-payrollmaster-salarylevelmaster-edit/{id}', 'PayrollMasterController@editSalaryLevel');
Route::post('/masterdata-payrollmaster-salarylevelmaster-edit/{id}', 'PayrollMasterController@doeditSalaryLevel');
Route::get('/masterdata-payrollmaster-salarylevelmaster-delete/{id}', 'PayrollMasterController@deleteSalaryLevel');
Route::post('/masterdata-payrollmaster-salarylevelmaster-search', 'PayrollMasterController@searchSalaryLevel');

// BPJS_Type_master
Route::get('/masterdata-payrollmaster-BPJStypemaster', 'PayrollMasterController@BPJSTypeMasterIndex');
Route::post('/masterdata-payrollmaster-BPJStypemaster-store', 'PayrollMasterController@BPJSTypeMasterStore');
Route::get('/masterdata-payrollmaster-BPJStypemaster-edit/{id}', 'PayrollMasterController@editBPJSType');
Route::post('/masterdata-payrollmaster-BPJStypemaster-edit/{id}', 'PayrollMasterController@doeditBPJSType');
Route::get('/masterdata-payrollmaster-BPJStypemaster-delete/{id}', 'PayrollMasterController@deleteBPJSType');
Route::post('/masterdata-payrollmaster-BPJStypemaster-search', 'PayrollMasterController@searchBPJSType');


// ini untuk leave type master
// ini view
Route::get('/masterdata-payrollmaster-leavetypemaster', 'PayrollMasterController@LeaveTypeMasterIndex');
// ini untuk add
Route::post('/masterdata-payrollmaster-leavetypemaster-store', 'PayrollMasterController@LeaveTypeMasterStore');
// delete
Route::get('/masterdata-payrollmaster-leavetypemaster-delete/{id}', 'PayrollMasterController@deleteLeaveType');
// edit
Route::get('/masterdata-payrollmaster-leavetypemaster-edit/{id}', 'PayrollMasterController@editLeaveType');
Route::post('/masterdata-payrollmaster-leavetypemaster-edit/{id}', 'PayrollMasterController@doeditLeaveType');
// end leave type


// ini untuk incentive master
Route::get('/masterdata-payrollmaster-incentivemaster', 'PayrollMasterController@IncentiveMasterIndex');
Route::post('/masterdata-payrollmaster-incentivemaster-store', 'PayrollMasterController@IncentiveMasterStore');
Route::get('/masterdata-payrollmaster-incentivemaster-delete/{id}', 'PayrollMasterController@deleteIncentive');
Route::get('/masterdata-payrollmaster-incentivemaster-edit/{id}', 'PayrollMasterController@editIncentive');
Route::post('/masterdata-payrollmaster-incentivemaster-edit/{id}', 'PayrollMasterController@doeditIncentive');
// end incentive

// ini untuk pph master
Route::get('/masterdata-payrollmaster-PPHtypemaster', 'PayrollMasterController@PPHtypeMasterIndex');
Route::post('/masterdata-payrollmaster-PPHtypemaster-store', 'PayrollMasterController@PPHTypeMasterStore');
Route::get('/masterdata-payrollmaster-PPHtypemaster-delete/{id}', 'PayrollMasterController@deletePPH');
Route::get('/masterdata-payrollmaster-PPHtypemaster-edit/{id}', 'PayrollMasterController@editPPH');
Route::post('/masterdata-payrollmaster-PPHtypemaster-edit/{id}', 'PayrollMasterController@doeditPPH');
// end pph

// ini untuk PTKP Master
Route::get('/masterdata-payrollmaster-PTKPtypemaster', 'PayrollMasterController@PTKPTypeMasterIndex');
Route::post('/masterdata-payrollmaster-PTKPtypemaster-store', 'PayrollMasterController@PTKPTypeMasterStore');
Route::get('/masterdata-payrollmaster-PTKPtypemaster-delete/{id}', 'PayrollMasterController@deletePTKP');
Route::get('/masterdata-payrollmaster-PTKPtypemaster-edit/{id}', 'PayrollMasterController@editPTKP');
Route::post('/masterdata-payrollmaster-PTKPtypemaster-edit/{id}', 'PayrollMasterController@doeditPTKP');
// end PTKP


// ini untuk Working days Master
Route::get('/masterdata-payrollmaster-workingdaysmaster', 'PayrollMasterController@WorkingDaysMasterIndex');
// end Working days Master

// ini untuk submission form leave

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Session;
use App\Post;
use App\User;
use App\Todo;
use App\Absen;
use Alert;




class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'clearance'])->except('index', 'show');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();
        $news = Post::orderby('id', 'desc')->paginate(5, ['*'], 'news');
        $todo = Todo::orderby('id', 'desc')->where('user_id', Auth::user()->id)->paginate(5, ['*'], 'todo');
        $birth_now =  User::whereRaw("DATE_FORMAT(birthofdate, '%m-%d') = DATE_FORMAT(now(),'%m-%d')  ")
            ->orWhereRaw("DATE_FORMAT(birthofdate,'%m-%d') = '02-29' and DATE_FORMAT(birthofdate, '%m') = '02' AND 
        LAST_DAY(NOW()) = DATE(NOW())")
            ->get();

        

        return view('dashboard.dashboard', compact('news', 'todo', 'users', 'birth_now'));
    }

    public function addtodo(Request $request)
    {
        $todo = Todo::all();


        $newtodo = new Todo();
        $newtodo->todo = $request['todo'];
        $newtodo->user_id = Auth::user()->id;

        $newtodo->save();

        return redirect('dashboard')->with('info', 'Todo has been created.');
    }
    // delete todolist

    public function deletetodo($id)
    {
        $todo = Todo::find($id);
        $todo->delete();
        return redirect('dashboard')->with('danger', 'Todo has been deleted.');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('dashboard.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validating title and body field
        $this->validate($request, [
            'title' => 'required|max:100',
            'body' => 'required',
            'footer' => 'required',
        ]);

        $title = $request['title'];
        $body = $request['body'];   
        $footer = $request['footer'];
        $news = Post::create($request->only('title', 'body', 'footer'));

        //Display a successful message upon save
        Alert::success(' News has been created ', 'Success')->persistent("Close");
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $news = Post::findOrFail($id); //Find post of id = $id

        return view('dashboard.show', compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $news = Post::findOrFail($id);

        return view('dashboard.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'title' => 'required|max:100',
            'body' => 'required',
            'footer' => 'required',
        ]);

        $news = Post::findOrFail($id);
        $news->title = $request->input('title');
        $news->body = $request->input('body');
        $news->footer = $request->input('footer');
        $news->save();

        return redirect()->route(
            'dashboard.show',
            $news->id
        )->with(
            'flash_message',
            'Article, ' . $news->title . ' updated'
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $news = Post::findOrFail($id);
        $news->delete();

        return redirect("dashboard")
            ->with(
                'flash_message',
                'Article successfully deleted'
            );
    }
}

resources/views/dashboard/create.blade.php
@extends('layouts.app-spinner')
@section('content')
@can('News Master')

<section class="content">

    <body class="fix-header fix-sidebar card-no-border">
        <div id="main-wrapper">
            <div class="content-wrapper">
                <!-- ============================================================== -->
                <!-- Container fluid  -->
                <!-- ============================================================== -->
                <div class="container-fluid">
                    <!-- ============================================================== -->
                    <!-- Bread crumb and right sidebar toggle -->
                    <!-- ============================================================== -->
                    <div class="row page-titles">
                        <div class="col-md-12 col-8 align-self-center">
                            <h3 class="text-themecolor">Create News</h3>
                        </div>
                        <div class="col-md-12 col-8 align-self-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item active">Create News</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card">
                    @include('sweet::alert')
                    <div class="card-body">
                        <h4 class="card-title"> News</h4>
                        <hr>
                        <form action="{{route('dashboard.store')}}" class="form-horizontal" method="POST"
                            enctype="multipart/form-data">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label>Title</label>
                                <div class="input-group">
                                    <input type="text" name="title" class="form-control" placeholder="Enter title">
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Body</label>
                                <div class="input-group">
                                    <textarea class="summernote" name="body" rows="10">Enter Body</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Footer</label>
                                <div class="input-group">
                                    <input type="text" name="footer" class="form-control" placeholder="Enter footer">
                                </div>
                            </div>
                            <br>
                            <button type="submit"
                                class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
    </body>
    <script>
        $(function () {
            $('.summernote').summernote({
                height: 350, // set editor height
                minHeight: null, // set minimum height of editor
                maxHeight: null, // set maximum height of editor
                focus: false // set focus to editable area after initializing summernote
            });
            $('.inline-editor').summernote({
                airMode: true
            });
        });
        window.edit = function () {
            $(".click2edit").summernote()
        },
        window.save = function () {
            $(".click2edit").summernote('destroy');
        }
    </script>
</section>
@endcan
@endsection

resources/views/dashboard/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    
    <div class="col-md-8 col-md-offset-2">
        
        <h1>Edit News</h1>
        <hr>
        {{ Form::model($news, array('route' => array('dashboard.update', $news->id), 'method' => 'PUT')) }}
        <div class="form-group">
            {{ Form::label('title', 'Title') }}
            {{ Form::text('title', null, array('class' => 'form-control')) }}<br>
            {{ Form::label('body', 'Post Body') }}
            {{ Form::textarea('body', null, array('class' => 'form-control')) }}<br>            
            {{ Form::label('footer', 'Footer') }}
            {{ Form::text('footer', null, array('class' => 'form-control')) }}<br>           
            {{ Form::submit('Save Changes', array('class' => 'btn btn-primary')) }}
            
            {{ Form::close() }}
        </div>
    </div>
</div>

@endsection

resources/views/dashboard/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>{{ $news1->title }}</h1>
    <p class="lead">{{ $news1->body }}  
    </p>
    <hr>
    {!! Form::open(['method' => 'DELETE', 'route' => ['dashboard.destroy', $news1->id] ]) !!}
    <a href="{{ url()->previous() }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i></a>
    @can('Edit News')
    <a href="{{ route('dashboard.edit', $news1->id) }}" class="btn btn-info" role="button"><i class="fa fa-edit"></i></a>
    @endcan
    @can('Delete News')
    {{ Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm'] )  }}
    @endcan
    {!! Form::close() !!}
</div>

@endsection